name: Dev.to Blog Posts

on:
  schedule:
    - cron: '0 */12 * * *' # Runs every 12 hours
  workflow_dispatch: # Allows manual trigger

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update Dev.to Posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: 'https://dev.to/feed/maurya-sachin'
          max_post_count: 3
